name: personal_expenses
description: A Academind tutorial.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts: 
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
        weight: 700
    - family: Quicksand
      fonts:
      - asset: assets/fonts/Quicksand-Regular.ttf
      - asset: assets/fonts/Quicksand-Light.ttf
      - asset: assets/fonts/Quicksand-Medium.ttf
      - asset: assets/fonts/Quicksand-Bold.ttf
        weight: 700              